[phases.setup]
nixPkgs = ["python310", "gcc", "stdenv", "zlib", "glib", "libGL", "libglvnd"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install --no-cache-dir --timeout=1000 tensorflow-cpu==2.15.0",
    "pip install --no-cache-dir --timeout=1000 deepface==0.0.79",
    "pip install --no-cache-dir --timeout=1000 -r requirements.txt"
]

[phases.start]
cmd = ". /opt/venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
